# Generated by Django 5.2.8 on 2025-12-03 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_footer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('level', models.CharField(verbose_name=50)),
                ('mode', models.CharField(max_length=50)),
                ('video_url', models.TextField()),
                ('playlist_url', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Footer',
        ),
    ]
