# Generated by Django 5.2.8 on 2025-12-03 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_cources_delete_footer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cources',
            name='level',
            field=models.CharField(max_length=50),
        ),
    ]
