# Generated by Django 5.2.8 on 2025-12-03 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_playlists'),
    ]

    operations = [
        migrations.CreateModel(
            name='MostWatched',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video_url', models.TextField()),
            ],
        ),
    ]
