# Generated by Django 5.2.8 on 2025-12-03 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_mostwatched'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MostWatched',
            new_name='MostPopular',
        ),
    ]
